### PR TITLE
add minimum type declarations

### PR DESCRIPTION
**Pull request by robjweiss**
A base for type declarations for the module. It would be great to complete it in the future.

### CODE REVIEW

**Review by naggingant — COMMENTED** [review]
Thanks for adding this
Did you follow some practice for how to add only type declarations to an existing project? I thought, the types would not be exported unless package.json has `"types": "index.d.ts"`, or something like that

Also, can you try resaving the file after adding the editorconfig plugin to your text editor, please? Then the lack of newline at the end of the file should be gone

**Comment by robjweiss** [comment]
I can't find the original reference I used, but this talks about the resolution for declarations: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#editing-the-packagejson.

We can add the types field, it's optional in this case since the file is named index and at the root. Let me know if you'd prefer that.

**Comment by naggingant** [comment]
@robjweiss thanks for the clarification
I have got another question actually, don't we have to add dependency to the referenced types like Express.* ? Sorry it's more like TS basics that I am asking

Edit: I couldn't find a good example of a JS library that has type definitions for _properly_ importing it in TS. Perhaps you had something you followed?

**Comment by robjweiss** [comment]
Here Express is a reference to the Express namespace (https://www.typescriptlang.org/docs/handbook/namespaces.html). So we don't have to import it directly I think.

**Comment by naggingant** [comment]
But unlike some builtin namespaces like NodeJS, I think we have to import the namespace from `@types/express`. I'm almost pretty certain
Did you try building your code that imports this library, with `skipLibCheck: false`?

**Comment by robjweiss** [comment]
I'm not sure why it doesn't complain about it, but I agree, I added the import.

**Review by naggingant — APPROVED** [review]

**Pull request merged**
